"""add_created_by_to_problems_lessons

Revision ID: 1b58cd072ab3
Revises: 3cd18e412494
Create Date: 2026-08-09 06:45:02.282868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b58cd072ab3'
down_revision: Union[str, None] = '3cd18e412494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('created_by_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_lessons_created_by_id'), 'lessons', ['created_by_id'], unique=False)
    op.create_foreign_key(None, 'lessons', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('problems', sa.Column('created_by_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_problems_created_by_id'), 'problems', ['created_by_id'], unique=False)
    op.create_foreign_key(None, 'problems', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'problems', type_='foreignkey')
    op.drop_index(op.f('ix_problems_created_by_id'), table_name='problems')
    op.drop_column('problems', 'created_by_id')
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_index(op.f('ix_lessons_created_by_id'), table_name='lessons')
    op.drop_column('lessons', 'created_by_id')
    # ### end Alembic commands ###
