"""add_interactive_quiz_features

Revision ID: 4497d69a0a97
Revises: 1b58cd072ab3
Create Date: 2026-08-09 15:37:59.320352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4497d69a0a97'
down_revision: Union[str, None] = '1b58cd072ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_quizzes', sa.Column('correct_answers_json', sa.Text(), nullable=True))
    op.add_column('lesson_quizzes', sa.Column('quiz_type', sa.String(length=30), nullable=False, server_default='single'))
    op.alter_column('lesson_quizzes', 'correct_option_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('user_lesson_progress', sa.Column('solved_quizzes_json', sa.Text(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_lesson_progress', 'solved_quizzes_json')
    op.alter_column('lesson_quizzes', 'correct_option_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('lesson_quizzes', 'quiz_type')
    op.drop_column('lesson_quizzes', 'correct_answers_json')
    # ### end Alembic commands ###
