"""add_topic_data_pool

Revision ID: 61c3472fbdf8
Revises: 18fa6032a363
Create Date: 2026-08-09 02:37:46.068329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61c3472fbdf8'
down_revision: Union[str, None] = '18fa6032a363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_data_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content_mongolian', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'REJECTED', name='curatordatastatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_data_pool_id'), 'topic_data_pool', ['id'], unique=False)
    op.create_index(op.f('ix_topic_data_pool_status'), 'topic_data_pool', ['status'], unique=False)
    op.create_index(op.f('ix_topic_data_pool_topic'), 'topic_data_pool', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_data_pool_topic'), table_name='topic_data_pool')
    op.drop_index(op.f('ix_topic_data_pool_status'), table_name='topic_data_pool')
    op.drop_index(op.f('ix_topic_data_pool_id'), table_name='topic_data_pool')
    op.drop_table('topic_data_pool')
    # ### end Alembic commands ###
