"""add_vector_indexing_to_curator

Revision ID: 951896d9dfcd
Revises: ee3711bc3330
Create Date: 2026-08-09 18:59:41.659999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '951896d9dfcd'
down_revision: Union[str, None] = 'ee3711bc3330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_data_pool', sa.Column('is_vector_indexed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('topic_data_pool', sa.Column('qdrant_point_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic_data_pool', 'qdrant_point_id')
    op.drop_column('topic_data_pool', 'is_vector_indexed')
    # ### end Alembic commands ###
