"""add_classroom_enrollment_status_and_lesson_classroom_id

Revision ID: e105e10d5706
Revises: 4497d69a0a97
Create Date: 2026-08-09 16:12:42.318395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e105e10d5706'
down_revision: Union[str, None] = '4497d69a0a97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classroom_students', sa.Column('status', sa.String(length=30), nullable=False))
    op.add_column('lessons', sa.Column('classroom_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lessons', 'classrooms', ['classroom_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_column('lessons', 'classroom_id')
    op.drop_column('classroom_students', 'status')
    # ### end Alembic commands ###
