"""add actual_output column

Revision ID: ea6cdd0baf65
Revises: a2a2a2a2a2a2
Create Date: 2026-08-10 10:07:13.858830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea6cdd0baf65'
down_revision: Union[str, None] = 'a2a2a2a2a2a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('judge_results', sa.Column('actual_output', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('judge_results', 'actual_output')
    # ### end Alembic commands ###
