"""pattern3_classroom_lessons_many_to_many

Revision ID: ee3711bc3330
Revises: e105e10d5706
Create Date: 2026-08-09 16:30:19.859478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee3711bc3330'
down_revision: Union[str, None] = 'e105e10d5706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom_lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classroom_id', 'lesson_id', name='uq_classroom_lesson')
    )
    op.create_index(op.f('ix_classroom_lessons_id'), 'classroom_lessons', ['id'], unique=False)
    op.add_column('lessons', sa.Column('is_public', sa.Boolean(), server_default='true', nullable=False))
    op.drop_constraint('lessons_classroom_id_fkey', 'lessons', type_='foreignkey')
    op.drop_column('lessons', 'classroom_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('classroom_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('lessons_classroom_id_fkey'), 'lessons', 'classrooms', ['classroom_id'], ['id'], ondelete='SET NULL')
    op.drop_column('lessons', 'is_public')
    op.drop_index(op.f('ix_classroom_lessons_id'), table_name='classroom_lessons')
    op.drop_table('classroom_lessons')
    # ### end Alembic commands ###
